(() => {
  'use strict';
  const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));const money=v=>`KSh ${Number(v||0).toLocaleString('en-KE')}`;const when=v=>v?new Date(v).toLocaleString('en-KE',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}):'—';
  async function req(path,options={}){if(window.LuneData?.request)return window.LuneData.request(path,options);const r=await fetch(`/api${path}`,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...options,body:options.body&&typeof options.body!=='string'?JSON.stringify(options.body):options.body});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||`request_failed_${r.status}`);return d}
  let overview={},partners=[],orders=[],payouts=[],payoutSummary={},offers=[];
  function statCount(rows,key){return (rows||[]).reduce((s,r)=>s+Number(r[key]||0),0)}
  function renderStats(){const paid=(overview.payments||[]).find(x=>x.payment_status==='paid');const payable=(overview.payouts||[]).filter(x=>['payable','processing'].includes(x.status)).reduce((s,x)=>s+Number(x.value_kes||0),0);$('[data-admin-stats]').innerHTML=`<div class="dashboard-stat"><span>Orders</span><strong>${statCount(overview.orders,'count')}</strong></div><div class="dashboard-stat"><span>Pending matches</span><strong>${Number(overview.pendingRequests||0)}</strong></div><div class="dashboard-stat"><span>Paid value</span><strong>${money(paid?.value_kes||0)}</strong></div><div class="dashboard-stat"><span>Partner owed</span><strong>${money(payoutSummary.unpaid||payable)}</strong></div>`}
  function renderPartners(){const select=$('[data-location-form] select[name="partnerId"]');select.innerHTML=partners.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');$('[data-partner-list]').innerHTML=partners.length?partners.map(p=>`<article class="dashboard-row"><div><div class="eyebrow">${esc(p.status)}</div><h3>${esc(p.name)}</h3><p>${Number(p.locations||0)} station${Number(p.locations||0)===1?'':'s'} · ${Number(p.members||0)} member${Number(p.members||0)===1?'':'s'} · ${(Number(p.commission_bps||0)/100).toFixed(1)}% Lune</p><p class="ops-muted">${esc(p.id)}</p></div></article>`).join(''):'<div class="ops-empty">No partners yet.</div>'}
  function renderOrders(){$('[data-admin-orders]').innerHTML=orders.length?orders.map(o=>`<article class="dashboard-row" data-order="${esc(o.id)}"><div><div class="eyebrow">${esc(String(o.status||'').replace(/_/g,' '))} · ${esc(o.payment_status||'unpaid')}</div><h3>${esc(o.item_snapshot?.title||'Lune order')}</h3><p>${esc(o.customer_name||'Client')} · ${esc(when(o.scheduled_for))} · ${esc(o.location_name||'Not allocated')}</p><p>${money(o.amount_kes)} · ${esc(o.partner_name||'No partner yet')}</p></div><div class="ops-actions"><button class="ops-button quiet" type="button" data-reallocate>Reallocate</button>${o.payment_status==='paid'?'<button class="ops-button danger" type="button" data-refund>Refund</button>':''}</div></article>`).join(''):'<div class="ops-empty">No orders yet.</div>'}
  function renderPayouts(){const summary=`<div class="dashboard-row"><div><div class="eyebrow">SETTLEMENT LEDGER</div><h3>${money(payoutSummary.unpaid||0)} still owed to partners</h3><p>Held ${money(payoutSummary.held||0)} · ready ${money(payoutSummary.ready||0)} · processing ${money(payoutSummary.processing||0)} · failed ${money(payoutSummary.failed||0)}</p><p class="ops-muted">Held becomes payable only after the appointment is completed. Paid and reversed transfers are excluded from the amount owed.</p></div><div class="ops-actions"><button class="ops-button quiet" type="button" data-email-test>Send me a delivery test</button></div></div>`;$('[data-payout-list]').innerHTML=summary+(payouts.length?payouts.map(p=>`<article class="dashboard-row" data-payout="${esc(p.id)}"><div><div class="eyebrow">${esc(p.status)}</div><h3>${esc(p.partner_name||'Partner')}</h3><p>${money(p.net_kes)} · order ${esc(p.order_id)}</p></div><div class="ops-actions">${p.status==='payable'?'<button class="ops-button" type="button" data-send-payout>Send payout</button>':''}</div></article>`).join(''):'<div class="ops-empty">No partner payouts yet.</div>')}
  function renderOffers(){$('[data-offer-list]').innerHTML=offers.length?offers.map(o=>`<article class="dashboard-row" data-offer="${esc(o.id)}"><div><div class="eyebrow">${o.active?'ACTIVE':'OFF'}</div><h3>${esc(o.title)}</h3><p>${esc(o.code)} · ${esc(o.copy||'')}</p></div><button class="ops-button quiet" type="button" data-toggle-offer>${o.active?'Pause':'Activate'}</button></article>`).join(''):'<div class="ops-empty">No offers yet.</div>'}
  function render(){renderStats();renderPartners();renderOrders();renderPayouts();renderOffers()}
  async function load(){try{const access=await req('/access');if(!access.isAdmin)throw new Error(access.user?'admin_required':'authentication_required');const payoutsResult=await req('/admin/payouts');[overview,partners,orders,payouts,payoutSummary,offers]=await Promise.all([req('/admin/overview'),req('/admin/partners').then(x=>x.partners||[]),req('/admin/orders').then(x=>x.orders||[]),Promise.resolve(payoutsResult.payouts||[]),Promise.resolve(payoutsResult.summary||{}),req('/admin/offers').then(x=>x.offers||[])]);$('[data-admin-locked]').classList.add('ops-hidden');$('[data-admin-content]').classList.remove('ops-hidden');render()}catch(err){if(['authentication_required','admin_required'].includes(err.message)){$('[data-admin-locked]').classList.remove('ops-hidden');$('[data-admin-content]').classList.add('ops-hidden');return}const lock=$('[data-admin-locked]');lock.classList.remove('ops-hidden');lock.querySelector('h2').textContent='Operations unavailable.';lock.querySelector('p').textContent='Try again shortly.'}}
  function status(node,msg,err=false){node.textContent=msg||'';node.classList.toggle('is-error',err)}
  $('[data-partner-form]')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,s=$('[data-partner-status]');status(s,'');try{const d=await req('/admin/partners',{method:'POST',body:{name:f.elements.name.value,email:f.elements.email.value||null,commissionBps:Math.round(Number(f.elements.commission.value||0)*100),status:'active'}});status(s,`Partner created: ${d.id}`);f.reset();await load()}catch(err){status(s,err.message,true)}});
  $('[data-location-form]')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,s=$('[data-location-status]');status(s,'');try{const tags=f.elements.tags.value.split(',').map(x=>x.trim()).filter(Boolean);const d=await req(`/admin/partners/${encodeURIComponent(f.elements.partnerId.value)}/locations`,{method:'POST',body:{name:f.elements.name.value,address:f.elements.address.value,area:f.elements.area.value,experienceTier:f.elements.experienceTier.value,experienceTags:tags,email:f.elements.email.value||null,googleMapsUrl:f.elements.map.value||null}});status(s,`Station created: ${d.id}`);f.reset();await load()}catch(err){status(s,err.message,true)}});
  $('[data-offer-form]')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,s=$('[data-offer-status]');status(s,'');const rule={};if(f.elements.savedMin.value!=='')rule.saved_min=Number(f.elements.savedMin.value);if(f.elements.completedMin.value!=='')rule.completed_min=Number(f.elements.completedMin.value);const reward=f.elements.type.value==='percent'?{type:'percent',percent:Number(f.elements.value.value)}:{type:'fixed_kes',amount:Number(f.elements.value.value)};try{await req('/admin/offers',{method:'POST',body:{code:f.elements.code.value,title:f.elements.title.value,copy:f.elements.copy.value,rule,reward,active:f.elements.active.checked,priority:0}});status(s,'Offer created.');f.reset();await load()}catch(err){status(s,err.message,true)}});
  document.addEventListener('click',async e=>{if(e.target.closest('[data-refresh]'))return load();if(e.target.closest('[data-email-test]')){const button=e.target.closest('[data-email-test]');button.disabled=true;try{const result=await req('/admin/email-test',{method:'POST',body:{}});alert(result.status==='sent'?'The email provider accepted a delivery test to your admin inbox.':'Email is not configured in this environment yet.');}catch(err){alert(err.message)}finally{button.disabled=false}}const order=e.target.closest('[data-order]');if(order&&e.target.closest('[data-reallocate]')){if(!confirm('Reallocate this order?'))return;try{await req(`/admin/orders/${encodeURIComponent(order.dataset.order)}/reallocate`,{method:'POST',body:{}});await load()}catch(err){alert(err.message)}}if(order&&e.target.closest('[data-refund]')){if(!confirm('Start a full refund for this order?'))return;try{await req(`/admin/orders/${encodeURIComponent(order.dataset.order)}/refund`,{method:'POST',body:{reason:'Admin refund'}});await load()}catch(err){alert(err.message)}}const payout=e.target.closest('[data-payout]');if(payout&&e.target.closest('[data-send-payout]')){if(!confirm('Send this partner payout?'))return;try{await req(`/admin/payouts/${encodeURIComponent(payout.dataset.payout)}/send`,{method:'POST',body:{}});await load()}catch(err){alert(err.message)}}const offer=e.target.closest('[data-offer]');if(offer&&e.target.closest('[data-toggle-offer]')){const current=offers.find(x=>x.id===offer.dataset.offer);try{await req(`/admin/offers/${encodeURIComponent(offer.dataset.offer)}`,{method:'PATCH',body:{active:!current.active}});await load()}catch(err){alert(err.message)}}});
  async function boot(){let i=0;while(!window.LuneData&&i++<30)await new Promise(r=>setTimeout(r,100));if(window.LuneData?.ready)await window.LuneData.ready.catch(()=>{});await load()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
