(() => {
  const $ = selector => document.querySelector(selector), params = new URLSearchParams(location.search);
  const esc = value => String(value || '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const visitor = () => window.LuneData?.visitorId || localStorage.getItem('lune_visitor_id_v1') || '';
  const request = async (path, options = {}) => { const response = await fetch(`/api${path}`, { credentials:'same-origin', headers:{'Content-Type':'application/json'}, ...options, body:options.body ? JSON.stringify(options.body) : undefined }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || 'request_failed'); return payload; };
  const voterKey = () => { let key = localStorage.getItem('lune_circle_voter'); if (!key) { key = crypto.randomUUID(); localStorage.setItem('lune_circle_voter',key); } return key; };
  const saved = () => { try { return { work:JSON.parse(localStorage.getItem('auranails_liked') || '[]'), inspo:JSON.parse(localStorage.getItem('aura_inspo_saved') || '[]') }; } catch { return {work:[],inspo:[]}; } };
  async function choose() { const stage=$('[data-pick-stage]'), keep=saved(); const [work,inspo]=await Promise.all([request('/catalog/work'),request('/catalog/inspo')]); const choices=[...(work.items||[]).filter(item=>keep.work.includes(item.id)).map(item=>({id:item.id,kind:'work',title:item.title,imageUrl:item.image_url||item.imageUrl})),...(inspo.items||[]).filter(item=>keep.inspo.some(savedItem=>savedItem.id===item.id)).map(item=>({id:item.id,kind:'inspo',title:item.title,imageUrl:item.image_url||item.imageUrl}))]; if(choices.length<2){stage.innerHTML='<div class="eyebrow">ONE MORE</div><h2>Save at least two sets first.</h2><p class="ops-muted">Then you can ask your people which direction feels most like you.</p><a class="ops-button" href="favorites.html">Open saved →</a>';return;} stage.innerHTML=`<div class="eyebrow">CHOOSE 2–4</div><h2>Which ones are still in the running?</h2><div class="match-list" data-choice-list>${choices.map(item=>`<label class="match-card"><input type="checkbox" value="${esc(item.id)}"><span><img src="${esc(item.imageUrl)}" alt="" style="width:56px;height:56px;object-fit:cover;border-radius:8px;vertical-align:middle;margin-right:12px"><strong>${esc(item.title)}</strong></span></label>`).join('')}</div><button class="ops-button lacquer" type="button" data-create-pick>Make a private link →</button><p class="ops-status" data-pick-status></p>`; stage.querySelector('[data-create-pick]').addEventListener('click',async()=>{const ids=[...stage.querySelectorAll('input:checked')].map(input=>input.value);const selected=choices.filter(item=>ids.includes(item.id));const status=$('[data-pick-status]');if(selected.length<2||selected.length>4){status.textContent='Choose between two and four sets.';return;}try{const pick=await request('/circle-picks',{method:'POST',body:{visitorId:visitor(),choices:selected}});await navigator.clipboard?.writeText(pick.url);status.innerHTML=`Your link is ready. <a href="${esc(pick.url)}">Open it</a> or send it to your people.`;}catch{status.textContent='Could not make the link. Try again.';}}); }
  async function vote(){const stage=$('[data-pick-stage]'),id=params.get('pick'),token=params.get('token');const data=await request(`/circle-picks/${encodeURIComponent(id)}?token=${encodeURIComponent(token)}`),pick=data.pick,votes=pick.votes||{};stage.innerHTML=`<div class="eyebrow">A SMALL OPINION, PLEASE</div><h2>Which one would you pick?</h2><p class="ops-muted">No account. No feed. Just the one you would want to see on their hands.</p><div class="match-list" data-vote-list>${pick.choices.map(choice=>`<button class="match-card" type="button" data-vote="${esc(choice.id)}"><span><img src="${esc(choice.imageUrl)}" alt="" style="width:72px;height:72px;object-fit:cover;border-radius:8px;vertical-align:middle;margin-right:12px"><strong>${esc(choice.title)}</strong></span><span>${Number(votes[choice.id]||0)} pick${Number(votes[choice.id]||0)===1?'':'s'}</span></button>`).join('')}</div><p class="ops-status" data-pick-status></p>`;stage.querySelectorAll('[data-vote]').forEach(button=>button.addEventListener('click',async()=>{await request(`/circle-picks/${encodeURIComponent(id)}/vote`,{method:'POST',body:{token,choiceId:button.dataset.vote,voterKey:voterKey()}});await vote();}));}
  async function boot(){try{if(params.get('pick')&&params.get('token')) await vote();else await choose();}catch{ $('[data-pick-stage]').innerHTML=params.get('pick')?'<h2>That pick link has passed.</h2><p class="ops-muted">Start another from your saved sets.</p><a class="ops-button" href="favorites.html">Open saved →</a>':'<h2>Your saved sets are taking a moment.</h2><p class="ops-muted">Try again shortly, or return to your shortlist.</p><a class="ops-button" href="favorites.html">Open saved →</a>'; }} if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
