(() => {
  'use strict';
  const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=v=>`KSh ${Number(v||0).toLocaleString('en-KE')}`;
  async function req(path,options={}){if(window.LuneData?.request)return window.LuneData.request(path,options);const r=await fetch(`/api${path}`,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...options,body:options.body&&typeof options.body!=='string'?JSON.stringify(options.body):options.body});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||`request_failed_${r.status}`);return d}
  const when=v=>v?new Date(v).toLocaleString('en-KE',{weekday:'short',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}):'—';
  let me=null,requests=[],orders=[],availability=[],partnerLocations=[],technicians=[];
  function locations(){const map=new Map();partnerLocations.filter(x=>x.active!==false).forEach(l=>map.set(l.id,l.name||l.id));(me?.memberships||[]).forEach(m=>{if(m.location_id&&!map.has(m.location_id))map.set(m.location_id,m.location_id)});requests.forEach(r=>map.set(r.location_id,r.location_name||r.location_id));orders.forEach(o=>{if(o.allocated_location_id)map.set(o.allocated_location_id,o.location_name||o.allocated_location_id)});return [...map.entries()]}
  function renderStats(){const today=new Date().toDateString();const todayOrders=orders.filter(o=>o.scheduled_for&&new Date(o.scheduled_for).toDateString()===today);const confirmed=todayOrders.filter(o=>!['completed','cancelled','no_show'].includes(o.status));const earning=todayOrders.reduce((s,o)=>s+Number(o.partner_earning_kes||0),0);$('[data-partner-stats]').innerHTML=`<div class="dashboard-stat"><span>Waiting</span><strong>${requests.length}</strong></div><div class="dashboard-stat"><span>Today</span><strong>${confirmed.length}</strong></div><div class="dashboard-stat"><span>Capacity blocks</span><strong>${availability.length}</strong></div><div class="dashboard-stat"><span>Today value</span><strong>${money(earning)}</strong></div>`}
  function renderRequests(){const t=$('[data-request-list]');if(!requests.length){t.innerHTML='<div class="ops-empty">No requests waiting. Lune will place the next suitable appointment here.</div>';return}t.innerHTML=requests.map(r=>`<article class="request-card" data-request="${esc(r.id)}"><img src="${esc(r.item_snapshot?.imageUrl||'inspo1.png.png')}" alt=""><div><div class="eyebrow">${esc(r.location_name||'LUNE')}</div><h3>${esc(r.item_snapshot?.title||'Appointment')}</h3><p>${esc(when(r.scheduled_for))} · ${esc(r.experience_preference||'Lune match')} · ${money(r.amount_kes)}</p><p>Respond by ${esc(when(r.expires_at))}</p></div><div class="ops-actions"><button class="ops-button lacquer" data-accept type="button">Accept</button><button class="ops-button quiet" data-decline type="button">Decline</button></div></article>`).join('');}
  function actionFor(o){const next={confirmed:['checked_in','Check in'],upcoming:['checked_in','Check in'],checked_in:['in_service','Start service'],in_service:['completed','Complete']}[o.status];return next?`<button class="ops-button" type="button" data-order-status="${next[0]}">${next[1]}</button>`:''}
  function renderOrders(){const t=$('[data-order-list]');if(!orders.length){t.innerHTML='<div class="ops-empty">No allocated appointments yet.</div>';return}t.innerHTML=orders.slice(0,100).map(o=>`<article class="dashboard-row" data-order="${esc(o.id)}"><div><div class="eyebrow">${esc(String(o.status||'').replace(/_/g,' '))}</div><h3>${esc(o.item_snapshot?.title||'Lune appointment')}</h3><p>${esc(when(o.scheduled_for))} · ${esc(o.location_name||'Station')} · ${esc(o.customer_name||'Client')}</p>${Number(o.party_size||1)>1?`<p class="ops-muted">Group booking · ${Number(o.party_size)} people</p>`:''}<p>${money(o.partner_earning_kes)} partner earning · ${esc(o.payment_status||'unpaid')}</p></div><div class="ops-actions">${actionFor(o)}</div></article>`).join('')}
  function renderTechnicians(){const select=$('[data-technician-select]');if(!select)return;const locationId=$('[data-capacity-form] select[name="locationId"]')?.value||'';const filtered=technicians.filter(t=>!locationId||t.location_id===locationId);select.innerHTML='<option value="">Any capable technician</option>'+filtered.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}${t.location_name?` · ${esc(t.location_name)}`:''}</option>`).join('')}
  function renderCapacity(){const select=$('[data-capacity-form] select[name="locationId"]');const locs=locations();const previous=select?.value||'';if(select){select.innerHTML=locs.length?locs.map(([id,name])=>`<option value="${esc(id)}">${esc(name)}</option>`).join(''):'<option value="">No location assigned</option>';if(previous&&locs.some(([id])=>id===previous))select.value=previous;}renderTechnicians();const t=$('[data-capacity-list]');t.innerHTML=availability.length?availability.map(a=>`<article class="dashboard-row" data-capacity="${esc(a.id)}"><div><h3>${esc(a.location_name||'Availability')}</h3><p>${esc(when(a.starts_at))} → ${esc(when(a.ends_at))}${a.technician_name?` · ${esc(a.technician_name)}`:''}</p></div><button class="ops-button quiet" data-remove-capacity type="button">Remove</button></article>`).join(''):'<div class="ops-empty">No upcoming capacity blocks yet.</div>'}
  function render(){renderStats();renderRequests();renderOrders();renderCapacity()}
  async function load(){try{me=await req('/partner/me');[requests,orders,availability,partnerLocations,technicians]=await Promise.all([req('/partner/requests').then(x=>x.requests||[]),req('/partner/orders').then(x=>x.orders||[]),req('/partner/availability').then(x=>x.availability||[]),req('/partner/locations').then(x=>x.locations||[]),req('/partner/technicians').then(x=>x.technicians||[])]);$('[data-partner-locked]').classList.add('ops-hidden');$('[data-partner-content]').classList.remove('ops-hidden');render()}catch(err){if(['authentication_required','partner_access_required'].includes(err.message)){$('[data-partner-locked]').classList.remove('ops-hidden');$('[data-partner-content]').classList.add('ops-hidden');return}const locked=$('[data-partner-locked]');locked.classList.remove('ops-hidden');locked.querySelector('h2').textContent='Partner dashboard unavailable.';locked.querySelector('p').textContent='Try again shortly.'}}
  document.addEventListener('change',e=>{if(e.target.matches('[data-capacity-form] select[name="locationId"]'))renderTechnicians()});
  document.addEventListener('click',async e=>{const card=e.target.closest('[data-request]');if(card&&e.target.closest('[data-accept]')){e.target.disabled=true;try{await req(`/partner/requests/${encodeURIComponent(card.dataset.request)}/accept`,{method:'POST',body:{}});await load()}catch(err){e.target.disabled=false;alert(err.message)}}if(card&&e.target.closest('[data-decline]')){const note=prompt('Optional note for Lune:')||'';e.target.disabled=true;try{await req(`/partner/requests/${encodeURIComponent(card.dataset.request)}/decline`,{method:'POST',body:{note}});await load()}catch(err){e.target.disabled=false;alert(err.message)}}const row=e.target.closest('[data-order]');const status=e.target.closest('[data-order-status]');if(row&&status){status.disabled=true;try{await req(`/partner/orders/${encodeURIComponent(row.dataset.order)}/status`,{method:'POST',body:{status:status.dataset.orderStatus}});await load()}catch(err){status.disabled=false;alert(err.message)}}const cap=e.target.closest('[data-capacity]');if(cap&&e.target.closest('[data-remove-capacity]')){try{await req(`/partner/availability/${encodeURIComponent(cap.dataset.capacity)}`,{method:'DELETE'});await load()}catch(err){alert(err.message)}}if(e.target.closest('[data-refresh]'))await load()});
  $('[data-capacity-form]')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,s=$('[data-capacity-status]');s.textContent='';try{if(!f.elements.locationId.value)throw new Error('location_required');await req('/partner/availability',{method:'POST',body:{locationId:f.elements.locationId.value,technicianId:f.elements.technicianId.value||null,startsAt:new Date(f.elements.startsAt.value).toISOString(),endsAt:new Date(f.elements.endsAt.value).toISOString()}});f.reset();s.textContent='Availability added.';await load()}catch(err){s.textContent=err.message;s.classList.add('is-error')}});
  async function boot(){let i=0;while(!window.LuneData&&i++<30)await new Promise(r=>setTimeout(r,100));if(window.LuneData?.ready)await window.LuneData.ready.catch(()=>{});await load();setInterval(load,30000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
